# Open in swagger editor: https://editor.swagger.io/
# for a quick preview
openapi: "3.0.0"
info:
  title: FastAPI
  version: 0.1.0
paths:
  /api/v1/external/session:
    get:
      tags:
        - External
      summary: Get Charging Metadata
      operationId: get_charging_metadata_api_v1_external_session_get
      security:
        - APIKeyHeader: []
        - OAuth2PasswordBearer: []
      parameters:
        - name: user_id
          in: query
          required: false
          schema:
            type: integer
            title: Id of the user
            description: Id of the user for which the user wants to retrieve charging sessions metadata (if not declared, returns all users)
          description: Id of the user for which the user wants to retrieve charging sessions metadata (if not declared, returns all users)
        - name: evse_id
          in: query
          required: false
          schema:
            type: string
            title: Id of the EVSE
            description: Id of the EVSE for which the user wants to retrieve charging sessions metadata (if not declared, returns all EVSEs)
          description: Id of the EVSE for which the user wants to retrieve charging sessions metadata (if not declared, returns all EVSEs)
        - name: session_id
          in: query
          required: false
          schema:
            type: string
            title: Id of the session
            description: Id of the session for which the user wants to retrieve metadata (if not declared, returns all sessions)
          description: Id of the session for which the user wants to retrieve metadata (if not declared, returns all sessions)
        - name: start_datetime
          in: query
          required: false
          schema:
            type: string
            format: date-time
            title: Request initial datetime filter
            description: Request initial datetime filter (in UTC) ['%Y-%m-%d %H:%M:%S '].
          description: Request initial datetime filter (in UTC) ['%Y-%m-%d %H:%M:%S '].
        - name: end_datetime
          in: query
          required: false
          schema:
            type: string
            format: date-time
            title: Request final datetime filter
            description: Request final datetime filter (in UTC) ['%Y-%m-%d %H:%M:%S '].
          description: Request final datetime filter (in UTC) ['%Y-%m-%d %H:%M:%S '].
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    session_id:
                      type: string
                      description: ID of the session
                    evse_id:
                      type: string
                      description: ID of the EVSE
                    user_id:
                      type: integer
                      description: ID of the user
                    start_time:
                      type: string
                      format: date-time
                      description: Beginning of the session
                    end_time:
                      type: string
                      format: date-time
                      description: End of the session
                    total_energy_transfered:
                      type: integer
                      description: Total energy transferred in the session, in Wh
                    max_power:
                      type: number
                      format: float
                      description: Maximum power output of the session, in W
                    min_power:
                      type: number
                      format: float
                      description: Minimum power output of the session, in W
                    states:
                      type: array
                      items:
                        type: object
                        properties:
                          datetime:
                            type: string
                            format: date-time
                            description: Timestamp of the instant
                          state:
                            type: string
                            description: State of the EVSE, starting at that instant
                    warnings:
                      type: string
                      description: Warnings related to the charging session
              examples:
                sample:
                  value:
                    - session_id: 000000000000020f
                      evse_id: a004
                      user_id: 14
                      start_time: '2024-01-16T13:47:00'
                      end_time: '2024-01-16T18:39:26'
                      total_energy_transfered: 6374
                      max_power: 3485
                      min_power: 777
                      states:
                        - datetime: '2024-01-16T11:45:04'
                          state: plugged_not_charging
                        - datetime: '2024-01-16T11:45:05'
                          state: charging
                        - datetime: '2024-01-16T13:47:00'
                          state: plugged_not_charging
                        - datetime: '2024-01-16T18:39:26'
                          state: not_plugged
                      warnings: ''
                    - session_id: 00000000000000b3
                      evse_id: a002
                      user_id: 17
                      start_time: '2024-01-16T16:18:28'
                      end_time: '2024-01-16T19:32:06'
                      total_energy_transfered: 4311
                      max_power: 3596
                      min_power: 840
                      states:
                        - datetime: '2024-01-16T14:57:10'
                          state: plugged_not_charging
                        - datetime: '2024-01-16T14:57:10'
                          state: charging
                        - datetime: '2024-01-16T14:57:11'
                          state: plugged_not_charging
                        - datetime: '2024-01-16T14:57:57'
                          state: charging
                        - datetime: '2024-01-16T16:18:28'
                          state: plugged_not_charging
                        - datetime: '2024-01-16T19:32:06'
                          state: not_plugged
                      warnings: ''
        '400':
          description: Session id defined without evse id
          content:
            application/json:
              example:
                detail: The session id can only be specified along with the evse id
        '403':
          description: Permission denied
          content:
            application/json:
              example:
                detail: You do not have permission to use this endpoint
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
        '500':
          description: Error in database access
          content:
            application/json:
              example:
                detail: 'Error accessing the data on database'

components:
  schemas:
    HTTPValidationError:
      type: object
      title: HTTPValidationError
      properties:
        detail:
          type: array
          title: Detail
          items:
            $ref: '#/components/schemas/ValidationError'
    ValidationError:
      type: object
      title: ValidationError
      required:
        - loc
        - msg
        - type
      properties:
        loc:
          type: array
          title: Location
          items:
            anyOf:
              - type: string
              - type: integer
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
  securitySchemes:
    APIKeyHeader:
      type: apiKey
      in: header
      name: x-api-key
    OAuth2PasswordBearer:
      type: oauth2
      flows:
        password:
          tokenUrl: "/api/v1/authenticate/access-token"
          scopes: {}